=== CSMona/ITI_9Months_Labs/XML/day_1/family.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ENTER_NAME_OF_ROOT_ELEMENT_HERE EMPTY>
<!ELEMENT family (grandfather)>
<!ELEMENT grandfather (#PCDATA|father|uncle|aunt)*>
<!ELEMENT father (#PCDATA|mother|daughter|son)*>
<!ELEMENT mother (name)>
<!ELEMENT daughter (#PCDATA|name)*>
<!ELEMENT son (#PCDATA)>
<!ELEMENT uncle (#PCDATA)>
<!ELEMENT aunt (#PCDATA)>
<!ELEMENT name (#PCDATA)>

<!ATTLIST father job (Engineer| Accountant| Doctor) "Engineer" > 

<!ATTLIST daughter age CDATA #REQUIRED>
<!ATTLIST daughter job CDATA #REQUIRED>
<!ATTLIST son age CDATA #REQUIRED>
<!ATTLIST son sport ( tennis | football ) "football"  >
<!ATTLIST aunt sons CDATA #IMPLIED>

=== CSMona/ITI_9Months_Labs/XML/day_1/family.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE family SYSTEM "family.dtd">
<family>
	<grandfather>Soliman
            <father job="Engineer" >Abdelmonem
			<mother>
				<name> mona</name>
			</mother>
			<daughter age="23" job="engineer">ghada</daughter>
			<son age="21" sport="football">mohamed</son>
		</father>
		<uncle>Ali</uncle>
		<uncle>Sami</uncle>
		
		<aunt sons="2">Noor</aunt>
	</grandfather>
</family>
